
"""
Course Number: ENGR 13300
Semester: e.g. Fall 2024

Description:
    Replace this line with a description of your program.

Assignment Information:
    Assignment:     e.g. 5.2.1 Py1 Team 1 (for Python 1 Team task 1)
    Team ID:        ### - ## (e.g. LC1 - 01; for section LC1, team 01)
    Author:         Name, login@purdue.edu
    Date:           e.g. 08/29/2024

Contributors:
    Name, login@purdue [repeat for each]

    My contributor(s) helped me:
    [ ] understand the assignment expectations without
        telling me how they will approach it.
    [ ] understand different ways to think about a solution
        without helping me plan my solution.
    [ ] think through the meaning of a specific error or
        bug present in my code without looking at my code.
    Note that if you helped somebody else with their code, you
    have to list that person as a contributor here as well.

Academic Integrity Statement:
    I have not used source code obtained from any unauthorized
    source, either modified or unmodified; nor have I provided
    another student access to my code.  The project I am
    submitting is my own original work.
"""

""" Write any import statements here (and delete this line)."""

from math import pi
from py2_team_3_heater_3 import heater
from py2_team_3_turbinepower_3 import turbine_power

def main():
    bl = 50
    density = 1.23
    C = 0.4
    wv = float(input("Enter the velocity in m/s: "))
    t = float(input("Enter the time in hours: "))
    powerGenerated = turbine_power(bl,density,wv,C)
    heatGenerated = heater(powerGenerated, t)
    print(f'The power generated by the turbine is {powerGenerated:.1f} W')
    print(f'The amount of heat output by the heater is {heatGenerated:.1f} J')

    #comments!


if __name__ == "__main__":
    main()
